name: Deploy Traefik Container

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Enable Port 80 and 443 on VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          port: ${{ secrets.VM_SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSWORD }}
          script: |
            sudo ufw allow 80/tcp
            sudo ufw allow 443/tcp
            sudo systemctl restart ufw

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_CF_DNS_API_TOKEN: ${{ secrets.CF_DNS_API_TOKEN}}
          envkey_DOMAIN: ${{ secrets.DOMAIN}}
          envkey_ACME_CA_SERVER: ${{secrets.ACME_CA_SERVER}}
          envkey_ACME_EMAIL: ${{ secrets.ACME_EMAIL }}
          envKey_TRAEFIK_DASHBOARD_DOMAIN_PREFIX: ${{ secrets.TRAEFIK_DASHBOARD_DOMAIN_PREFIX}}
          envkey_TRAEFIK_DASHBOARD_CREDENTIALS: ${{ secrets.TRAEFIK_DASHBOARD_CREDENTIALS }}
          file_name: .env
          fail_on_empty: false
          sort_keys: false

      - name: Copy envfile and project to VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          port: ${{ secrets.VM_SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSWORD }}
          source: ".env,."
          target: "traefik"
          rm: true

      - name: Deploy using Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          port: ${{ secrets.VM_SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSWORD }}
          script: |
            docker network create proxy
            cd traefik
            docker compose down
            docker compose up --build -d
